import {
  Tender,
  Bid,
  DocumentRecord,
  ComplianceAnalysis,
  RiskAssessment,
  AuditLog,
  ComplianceResultItem,
} from "@/types";

export const PRESENTATION_TENDER_ID = "tnd-001";

export const presentationTender: Tender = {
  _id: PRESENTATION_TENDER_ID,
  tenderId: "TND-2026-MNRE-0842",
  title: "Implementation of 500MW Grid-Connected Solar Photovoltaic & Energy Storage Infrastructure",
  description:
    "Turnkey design, engineering, supply, erection, testing and commissioning of 500MW utility-scale Solar PV power generating units with Battery Energy Storage Systems (BESS) across western regional zones under GeM procurement framework.",
  organizationId: "org-gov-001",
  authority: "Ministry of New and Renewable Energy (MNRE)",
  department: "Solar Energy Directorate",
  location: "Western Regional Grid (Rajasthan / Gujarat)",
  estimatedValue: 2400000000, // INR 2,400 Crore
  emdAmount: 48000000,
  tenderFee: 25000,
  category: "Renewable Energy & Infrastructure",
  status: "UNDER_EVALUATION",
  publication: {
    publishedAt: "2026-02-01T10:00:00Z",
    submissionDeadline: "2026-03-30T17:00:00Z",
    openingDate: "2026-03-31T11:00:00Z",
  },
  eligibilityCriteria: [
    "Minimum 5 years of experience in EPC of grid-connected solar power projects",
    "Audited annual financial turnover exceeding INR 150 Crore in each of the last three financial years",
    "Valid ISO 9001, ISO 14001 and ISO 45001 certifications",
    "Valid Class-A Electrical Contractor license issued by competent authority",
    "OEM Authorization letter for inverters & modules from tier-1 manufacturers",
  ],
  technicalRequirements: [
    {
      _id: "req-001",
      tenderId: PRESENTATION_TENDER_ID,
      category: "TECHNICAL",
      title: "Tier-1 Mono-PERC Solar Cell Minimum Efficiency",
      description:
        "All solar photovoltaic modules must employ Tier-1 Mono-PERC technology with minimum measured module efficiency of 21.5% under standard test conditions (STC).",
      type: "NUMERIC",
      mandatory: true,
      order: 1,
    },
    {
      _id: "req-002",
      tenderId: PRESENTATION_TENDER_ID,
      category: "CERTIFICATION",
      title: "Mandatory BIS & IEC Compliance Standards",
      description:
        "Modules and inverters must comply with IEC 61215, IEC 61730 Part 1 & 2, and have valid Bureau of Indian Standards (BIS) Registration under the CRS scheme (IS 14286).",
      type: "DOCUMENT",
      mandatory: true,
      order: 2,
    },
    {
      _id: "req-003",
      tenderId: PRESENTATION_TENDER_ID,
      category: "FINANCIAL",
      title: "Minimum Net Worth and Working Capital Facility",
      description:
        "Positive net worth of at least INR 50 Crore and a sanctioned working capital credit line of minimum INR 30 Crore from a scheduled commercial bank.",
      type: "FINANCIAL",
      mandatory: true,
      order: 3,
    },
    {
      _id: "req-004",
      tenderId: PRESENTATION_TENDER_ID,
      category: "COMPLIANCE",
      title: "Domestic Content Requirement (DCR) Compliance",
      description:
        "Declaration and verification that solar cells and modules are manufactured domestically in India in compliance with MNRE DCR norms (minimum 60% local content).",
      type: "BOOLEAN",
      mandatory: true,
      order: 4,
    },
    {
      _id: "req-005",
      tenderId: PRESENTATION_TENDER_ID,
      category: "TECHNICAL",
      title: "Comprehensive 5-Year Performance & O&M Guarantee",
      description:
        "Vendor must provide a minimum 5-year comprehensive operation and maintenance warranty with guaranteed annual performance ratio (PR) >= 78%.",
      type: "DOCUMENT",
      mandatory: false,
      order: 5,
    },
    {
      _id: "req-006",
      tenderId: PRESENTATION_TENDER_ID,
      category: "ELIGIBILITY",
      title: "GST Registration & Active Portal Status",
      description:
        "Mandatory active GSTIN registration with matching legal entity name and clear tax compliance filing records.",
      type: "DOCUMENT",
      mandatory: true,
      order: 6,
    },
    {
      _id: "req-007",
      tenderId: PRESENTATION_TENDER_ID,
      category: "ELIGIBILITY",
      title: "Permanent Account Number (PAN) Verification",
      description:
        "Valid PAN card copy matching bidder organizational details verified against Income Tax department database.",
      type: "DOCUMENT",
      mandatory: true,
      order: 7,
    },
    {
      _id: "req-008",
      tenderId: PRESENTATION_TENDER_ID,
      category: "COMPLIANCE",
      title: "Non-Blacklisting & Debarment Verification",
      description:
        "Sworn affidavit confirming vendor has not been debarred or blacklisted by Central/State Governments or GeM portal.",
      type: "BOOLEAN",
      mandatory: true,
      order: 8,
    },
    {
      _id: "req-009",
      tenderId: PRESENTATION_TENDER_ID,
      category: "CERTIFICATION",
      title: "OEM Authorization Letter for Key Components",
      description:
        "Manufacturer Authorization Form (MAF) from Tier-1 Solar Module & Central Inverter manufacturers authorizing bidder to quote.",
      type: "DOCUMENT",
      mandatory: true,
      order: 9,
    },
    {
      _id: "req-010",
      tenderId: PRESENTATION_TENDER_ID,
      category: "FINANCIAL",
      title: "Average Annual Audited Turnover Threshold",
      description:
        "Audited annual financial turnover exceeding INR 150 Crore in each of the last three financial years (FY 2022-23, 2023-24, 2024-25).",
      type: "FINANCIAL",
      mandatory: true,
      order: 10,
    },
  ],
  documentIds: ["doc-tnd-001"],
  createdBy: "usr-off-001",
  createdAt: "2026-02-01T09:30:00Z",
};

// ----------------------------------------------------
// 4 PRECONFIGURED BIDDERS FOR PRESENTATION SCENARIO
// ----------------------------------------------------

export const presentationBids: Bid[] = [
  {
    _id: "bid-001",
    tenderId: PRESENTATION_TENDER_ID,
    vendorOrganizationId: "org-ven-001",
    vendorName: "Tata Power Renewable Energy Limited",
    submittedBy: "usr-ven-001",
    status: "UNDER_REVIEW",
    submittedAt: "2026-02-28T11:10:00Z",
    documentIds: ["doc-bid-001-gst", "doc-bid-001-pan", "doc-bid-001-tech", "doc-bid-001-fin", "doc-bid-001-oem"],
    complianceAnalysisId: "cmp-001",
    complianceScore: 96,
    riskLevel: "LOW",
    createdAt: "2026-02-28T10:45:00Z",
  },
  {
    _id: "bid-002",
    tenderId: PRESENTATION_TENDER_ID,
    vendorOrganizationId: "org-ven-002",
    vendorName: "Adani Green Energy Systems Ltd",
    submittedBy: "usr-ven-002",
    status: "UNDER_REVIEW",
    submittedAt: "2026-03-01T09:15:00Z",
    documentIds: ["doc-bid-002-tech", "doc-bid-002-statutory"],
    complianceAnalysisId: "cmp-002",
    complianceScore: 82,
    riskLevel: "MEDIUM",
    createdAt: "2026-03-01T08:30:00Z",
  },
  {
    _id: "bid-003",
    tenderId: PRESENTATION_TENDER_ID,
    vendorOrganizationId: "org-ven-003",
    vendorName: "Vertex Infotech & Power Solutions Pvt Ltd",
    submittedBy: "usr-ven-003",
    status: "UNDER_REVIEW",
    submittedAt: "2026-03-02T14:20:00Z",
    documentIds: ["doc-bid-003-tech"],
    complianceAnalysisId: "cmp-003",
    complianceScore: 48,
    riskLevel: "HIGH",
    createdAt: "2026-03-02T13:40:00Z",
  },
  {
    _id: "bid-004",
    tenderId: PRESENTATION_TENDER_ID,
    vendorOrganizationId: "org-ven-004",
    vendorName: "Evergreen Energy Private Limited",
    submittedBy: "usr-ven-004",
    status: "UNDER_REVIEW",
    submittedAt: "2026-03-03T16:00:00Z",
    documentIds: ["doc-bid-004-tech"],
    complianceAnalysisId: "cmp-004",
    complianceScore: 78,
    riskLevel: "MEDIUM",
    createdAt: "2026-03-03T15:10:00Z",
  },
];

// ----------------------------------------------------
// COMPLIANCE ANALYSES FOR ALL 4 BIDDERS
// ----------------------------------------------------

export const presentationComplianceAnalyses: ComplianceAnalysis[] = [
  // BIDDER A: COMPLIANT / LOW RISK (Score: 96%)
  {
    _id: "cmp-001",
    tenderId: PRESENTATION_TENDER_ID,
    tenderTitle: presentationTender.title,
    bidId: "bid-001",
    vendorName: "Tata Power Renewable Energy Limited",
    score: 96,
    compliantCount: 10,
    reviewRequiredCount: 0,
    nonCompliantCount: 0,
    riskLevel: "LOW",
    status: "COMPLETED",
    createdAt: "2026-03-01T14:30:00Z",
    results: [
      {
        _id: "res-001-1",
        requirementId: "req-001",
        requirementTitle: "Tier-1 Mono-PERC Solar Cell Minimum Efficiency",
        category: "TECHNICAL",
        mandatory: true,
        result: "COMPLIANT",
        confidence: 0.98,
        explanation:
          "Datasheet in Technical Bid Section 4.2 confirms supply of 545Wp Mono-PERC bifacial modules with certified STC conversion efficiency of 21.8%, surpassing the required threshold of 21.5%.",
        reviewStatus: "VERIFIED",
        debertaClassification: {
          category: "TECHNICAL_ELIGIBILITY",
          confidence: 0.965,
          modelVersion: "microsoft/deberta-v3-base",
        },
        nliResult: {
          status: "SUPPORTS",
          explanation: "NLI model verified document evidence strongly supports requirement efficiency specification.",
          confidence: 0.952,
          modelVersion: "DeBERTa-v3-nli",
        },
        ruleEvaluation: {
          rule: "TECHNICAL_EFFICIENCY_CHECK",
          extractedValue: "21.8%",
          thresholdValue: "21.5%",
          passed: true,
        },
        evidence: {
          _id: "ev-001-1",
          documentId: "doc-bid-001-tech",
          documentName: "Tata_Power_Technical_Proposal_Vol_I.pdf",
          requirementId: "req-001",
          bidId: "bid-001",
          pageNumber: 24,
          clauseReference: "Clause 4.2.1 — Module Electrical Specifications",
          extractedText:
            "Module Type: TP-PERC-545B; STC Maximum Power: 545 Wp; Module Efficiency under Standard Test Conditions: 21.8%; Temperature Coefficient of Pmax: -0.34%/°C.",
          confidence: 0.98,
          boundingBox: { x: 48, y: 180, width: 510, height: 95 },
        },
      },
      {
        _id: "res-001-2",
        requirementId: "req-002",
        requirementTitle: "Mandatory BIS & IEC Compliance Standards",
        category: "CERTIFICATION",
        mandatory: true,
        result: "COMPLIANT",
        confidence: 0.96,
        explanation:
          "Valid BIS Registration Certificate (R-41000921) and certified test laboratory reports for IEC 61215 and IEC 61730 Part 1 & 2 were submitted and successfully validated.",
        reviewStatus: "VERIFIED",
        statutoryVerification: {
          portal: "BIS",
          identifier: "R-41000921",
          status: "VERIFIED",
          verifiedName: "Tata Power Renewable Energy Limited",
          matchedName: "Tata Power Renewable Energy Limited",
          isMatch: true,
          environment: "DEMO / SYNTHETIC VERIFICATION DATA",
          verifiedAt: "2026-03-01T14:31:00Z",
        },
        evidence: {
          _id: "ev-001-2",
          documentId: "doc-bid-001-tech",
          documentName: "Tata_Power_Technical_Proposal_Vol_I.pdf",
          requirementId: "req-002",
          bidId: "bid-001",
          pageNumber: 8,
          clauseReference: "Certificate No. BIS/CRS/2025/R-41000921",
          extractedText:
            "This is to certify that Crystalline Silicon Terrestrial Photovoltaic Modules manufactured by applicant conform to IS 14286:2010 / IEC 61215:2005 and IS/IEC 61730 (Part 1 & 2):2004.",
          confidence: 0.96,
          boundingBox: { x: 60, y: 120, width: 490, height: 80 },
        },
      },
      {
        _id: "res-001-3",
        requirementId: "req-003",
        requirementTitle: "Minimum Net Worth and Working Capital Facility",
        category: "FINANCIAL",
        mandatory: true,
        result: "COMPLIANT",
        confidence: 0.95,
        explanation:
          "Statutory auditor certificate verifies net worth of INR 412.8 Crore as of 31st March 2025. Bank solvency letter confirms sanctioned fund-based credit line of INR 75 Crore from State Bank of India.",
        reviewStatus: "VERIFIED",
        ruleEvaluation: {
          rule: "FINANCIAL_NET_WORTH_CHECK",
          extractedValue: "INR 412.8 Cr Net Worth / INR 75 Cr WC",
          thresholdValue: "INR 50 Cr Net Worth / INR 30 Cr WC",
          passed: true,
        },
        evidence: {
          _id: "ev-001-3",
          documentId: "doc-bid-001-fin",
          documentName: "Audited_Financial_Statements_and_Auditor_Certificate.pdf",
          requirementId: "req-003",
          bidId: "bid-001",
          pageNumber: 86,
          clauseReference: "Annexure F — Chartered Accountant Net Worth Certificate",
          extractedText:
            "We certify that the Net Worth of M/s Tata Power Renewable Energy Limited as on March 31, 2025 is INR 4,128.4 Million and Working Capital limits sanctioned stand at INR 750 Million.",
          confidence: 0.95,
          boundingBox: { x: 55, y: 310, width: 480, height: 70 },
        },
      },
      {
        _id: "res-001-4",
        requirementId: "req-004",
        requirementTitle: "Domestic Content Requirement (DCR) Compliance",
        category: "COMPLIANCE",
        mandatory: true,
        result: "COMPLIANT",
        confidence: 0.94,
        explanation:
          "DCR Undertaking affidavit provided in Form DCR-1 along with manufacturing facility inspection audit certificate for cell lines located in Tirunelveli, Tamil Nadu.",
        reviewStatus: "VERIFIED",
        evidence: {
          _id: "ev-001-4",
          documentId: "doc-bid-001-tech",
          documentName: "Tata_Power_Technical_Proposal_Vol_I.pdf",
          requirementId: "req-004",
          bidId: "bid-001",
          pageNumber: 104,
          clauseReference: "Section 9 — Domestic Content Requirement Undertaking",
          extractedText:
            "Solemn affirmation that 100% of solar photovoltaic cells and assembling modules proposed for this project are manufactured in India meeting MNRE Order No. 283/54/2018-Grid Solar.",
          confidence: 0.94,
          boundingBox: { x: 62, y: 220, width: 495, height: 85 },
        },
      },
      {
        _id: "res-001-5",
        requirementId: "req-005",
        requirementTitle: "Comprehensive 5-Year Performance & O&M Guarantee",
        category: "TECHNICAL",
        mandatory: false,
        result: "COMPLIANT",
        confidence: 0.92,
        explanation:
          "Vendor committed to 5-year O&M warranty with guaranteed 78.5% PR measured at 220kV interconnecting substation.",
        reviewStatus: "VERIFIED",
        evidence: {
          _id: "ev-001-5",
          documentId: "doc-bid-001-tech",
          documentName: "Tata_Power_Technical_Proposal_Vol_I.pdf",
          requirementId: "req-005",
          bidId: "bid-001",
          pageNumber: 68,
          clauseReference: "Clause 7.4 — Performance Ratio Guarantee",
          extractedText:
            "Annual Performance Ratio shall be guaranteed at 78.5% measured at the 220kV interconnecting substation with full 5-year comprehensive O&M coverage.",
          confidence: 0.92,
          boundingBox: { x: 50, y: 410, width: 500, height: 90 },
        },
      },
      {
        _id: "res-001-6",
        requirementId: "req-006",
        requirementTitle: "GST Registration & Active Portal Status",
        category: "ELIGIBILITY",
        mandatory: true,
        result: "COMPLIANT",
        confidence: 0.99,
        explanation: "Active GSTIN 07WKMCP4023I9ZY verified via GSTN API portal.",
        reviewStatus: "VERIFIED",
        statutoryVerification: {
          portal: "GST",
          identifier: "07WKMCP4023I9ZY",
          status: "VERIFIED",
          verifiedName: "Pragati Micro Control Systems Proprietorship",
          matchedName: "Pragati Micro Control Systems Proprietorship",
          isMatch: true,
          environment: "DEMO / SYNTHETIC VERIFICATION DATA",
          verifiedAt: "2026-03-01T14:31:05Z",
        },
        evidence: {
          _id: "ev-001-6",
          documentId: "doc-bid-001-gst",
          documentName: "01_GST_Certificate_Valid.pdf",
          requirementId: "req-006",
          bidId: "bid-001",
          pageNumber: 1,
          clauseReference: "Form GST REG-06",
          extractedText: "Registration Number: 07WKMCP4023I9ZY; Legal Name: Pragati Micro Control Systems Proprietorship.",
          confidence: 0.99,
          boundingBox: { x: 40, y: 100, width: 500, height: 120 },
        },
      },
      {
        _id: "res-001-7",
        requirementId: "req-007",
        requirementTitle: "Permanent Account Number (PAN) Verification",
        category: "ELIGIBILITY",
        mandatory: true,
        result: "COMPLIANT",
        confidence: 0.99,
        explanation: "PAN WKMCP4023I verified and matched with Income Tax department database.",
        reviewStatus: "VERIFIED",
        statutoryVerification: {
          portal: "PAN",
          identifier: "WKMCP4023I",
          status: "VERIFIED",
          verifiedName: "Pragati Micro Control Systems Proprietorship",
          matchedName: "Pragati Micro Control Systems Proprietorship",
          isMatch: true,
          environment: "DEMO / SYNTHETIC VERIFICATION DATA",
          verifiedAt: "2026-03-01T14:31:08Z",
        },
        evidence: {
          _id: "ev-001-7",
          documentId: "doc-bid-001-pan",
          documentName: "02_PAN_Card_Valid.pdf",
          requirementId: "req-007",
          bidId: "bid-001",
          pageNumber: 1,
          clauseReference: "PAN Card Document",
          extractedText: "Permanent Account Number: WKMCP4023I; Name: Pragati Micro Control Systems Proprietorship.",
          confidence: 0.99,
          boundingBox: { x: 50, y: 120, width: 450, height: 100 },
        },
      },
      {
        _id: "res-001-8",
        requirementId: "req-008",
        requirementTitle: "Non-Blacklisting & Debarment Verification",
        category: "COMPLIANCE",
        mandatory: true,
        result: "COMPLIANT",
        confidence: 0.98,
        explanation: "No active debarments found across Central Public Procurement Portal (CPPP) or GeM debarment lists.",
        reviewStatus: "VERIFIED",
        statutoryVerification: {
          portal: "DEBARMENT",
          identifier: "WKMCP4023I",
          status: "VERIFIED",
          verifiedName: "Pragati Micro Control Systems Proprietorship",
          matchedName: "Pragati Micro Control Systems Proprietorship",
          isMatch: true,
          isDebarred: false,
          environment: "DEMO / SYNTHETIC VERIFICATION DATA",
          verifiedAt: "2026-03-01T14:31:12Z",
        },
        evidence: {
          _id: "ev-001-8",
          documentId: "doc-bid-001-tech",
          documentName: "Tata_Power_Technical_Proposal_Vol_I.pdf",
          requirementId: "req-008",
          bidId: "bid-001",
          pageNumber: 112,
          clauseReference: "Annexure H — Non-Blacklisting Sworn Affidavit",
          extractedText: "We hereby solemnly affirm that M/s Tata Power Renewable Energy Limited has never been blacklisted or debarred by any Government entity.",
          confidence: 0.98,
          boundingBox: { x: 50, y: 300, width: 510, height: 80 },
        },
      },
      {
        _id: "res-001-9",
        requirementId: "req-009",
        requirementTitle: "OEM Authorization Letter for Key Components",
        category: "CERTIFICATION",
        mandatory: true,
        result: "COMPLIANT",
        confidence: 0.97,
        explanation: "Valid Tier-1 OEM authorization letter provided for string inverters and solar PV modules.",
        reviewStatus: "VERIFIED",
        evidence: {
          _id: "ev-001-9",
          documentId: "doc-bid-001-oem",
          documentName: "OEM_Authorization_Letter_TataPower.pdf",
          requirementId: "req-009",
          bidId: "bid-001",
          pageNumber: 1,
          clauseReference: "Manufacturer Authorization Form (MAF)",
          extractedText: "This is to authorize M/s Tata Power Renewable Energy Limited as our authorized system integrator for utility solar inverters.",
          confidence: 0.97,
          boundingBox: { x: 60, y: 150, width: 480, height: 90 },
        },
      },
      {
        _id: "res-001-10",
        requirementId: "req-010",
        requirementTitle: "Average Annual Audited Turnover Threshold",
        category: "FINANCIAL",
        mandatory: true,
        result: "COMPLIANT",
        confidence: 0.98,
        explanation: "Average 3-year turnover verified at INR 1,840 Crore (exceeding INR 150 Crore requirement).",
        reviewStatus: "VERIFIED",
        ruleEvaluation: {
          rule: "TURNOVER_THRESHOLD_CHECK",
          extractedValue: "INR 1,840 Crore",
          thresholdValue: "INR 150 Crore",
          passed: true,
        },
        evidence: {
          _id: "ev-001-10",
          documentId: "doc-bid-001-fin",
          documentName: "Audited_Financial_Statements_and_Auditor_Certificate.pdf",
          requirementId: "req-010",
          bidId: "bid-001",
          pageNumber: 4,
          clauseReference: "Financial Summary Table",
          extractedText: "FY 2022-23: ₹1,650 Cr; FY 2023-24: ₹1,890 Cr; FY 2024-25: ₹1,980 Cr. 3-Year Average: ₹1,840 Cr.",
          confidence: 0.98,
          boundingBox: { x: 50, y: 180, width: 500, height: 110 },
        },
      },
    ],
  },

  // BIDDER B: REVIEW REQUIRED / MEDIUM RISK (Score: 82%)
  {
    _id: "cmp-002",
    tenderId: PRESENTATION_TENDER_ID,
    tenderTitle: presentationTender.title,
    bidId: "bid-002",
    vendorName: "Adani Green Energy Systems Ltd",
    score: 82,
    compliantCount: 8,
    reviewRequiredCount: 2,
    nonCompliantCount: 0,
    riskLevel: "MEDIUM",
    status: "REQUIRES_REVIEW",
    createdAt: "2026-03-01T15:00:00Z",
    results: [
      {
        _id: "res-002-1",
        requirementId: "req-001",
        requirementTitle: "Tier-1 Mono-PERC Solar Cell Minimum Efficiency",
        category: "TECHNICAL",
        mandatory: true,
        result: "COMPLIANT",
        confidence: 0.95,
        explanation: "540Wp Mono-PERC modules with STC efficiency of 21.6% verified.",
        reviewStatus: "VERIFIED",
        evidence: {
          _id: "ev-002-1",
          documentId: "doc-bid-002-tech",
          documentName: "Adani_Green_Technical_Proposal.pdf",
          requirementId: "req-001",
          bidId: "bid-002",
          pageNumber: 18,
          clauseReference: "Technical Spec 3.1",
          extractedText: "Module Model: AG-540-PERC; Measured Efficiency: 21.6%.",
          confidence: 0.95,
          boundingBox: { x: 50, y: 140, width: 480, height: 80 },
        },
      },
      {
        _id: "res-002-2",
        requirementId: "req-002",
        requirementTitle: "Mandatory BIS & IEC Compliance Standards",
        category: "CERTIFICATION",
        mandatory: true,
        result: "COMPLIANT",
        confidence: 0.94,
        explanation: "Valid BIS CRS Registration R-41008812 verified.",
        reviewStatus: "VERIFIED",
        evidence: {
          _id: "ev-002-2",
          documentId: "doc-bid-002-tech",
          documentName: "Adani_Green_Technical_Proposal.pdf",
          requirementId: "req-002",
          bidId: "bid-002",
          pageNumber: 32,
          clauseReference: "BIS Certificate Section",
          extractedText: "BIS Registration R-41008812 covering IEC 61215 and IEC 61730.",
          confidence: 0.94,
          boundingBox: { x: 50, y: 200, width: 490, height: 70 },
        },
      },
      {
        _id: "res-002-3",
        requirementId: "req-003",
        requirementTitle: "Minimum Net Worth and Working Capital Facility",
        category: "FINANCIAL",
        mandatory: true,
        result: "COMPLIANT",
        confidence: 0.95,
        explanation: "CA Certificate confirms Net Worth of INR 380 Crore.",
        reviewStatus: "VERIFIED",
        evidence: {
          _id: "ev-002-3",
          documentId: "doc-bid-002-tech",
          documentName: "Adani_Green_Technical_Proposal.pdf",
          requirementId: "req-003",
          bidId: "bid-002",
          pageNumber: 62,
          clauseReference: "CA Net Worth Certificate",
          extractedText: "Net worth as on March 31, 2025: INR 3,800 Million.",
          confidence: 0.95,
          boundingBox: { x: 50, y: 280, width: 470, height: 75 },
        },
      },
      {
        _id: "res-002-4",
        requirementId: "req-004",
        requirementTitle: "Domestic Content Requirement (DCR) Compliance",
        category: "COMPLIANCE",
        mandatory: true,
        result: "COMPLIANT",
        confidence: 0.93,
        explanation: "DCR local content declared at 85%.",
        reviewStatus: "VERIFIED",
        evidence: {
          _id: "ev-002-4",
          documentId: "doc-bid-002-tech",
          documentName: "Adani_Green_Technical_Proposal.pdf",
          requirementId: "req-004",
          bidId: "bid-002",
          pageNumber: 74,
          clauseReference: "DCR Affidavit",
          extractedText: "Local manufacturing content calculated at 85.2%.",
          confidence: 0.93,
          boundingBox: { x: 50, y: 150, width: 460, height: 80 },
        },
      },
      {
        _id: "res-002-5",
        requirementId: "req-005",
        requirementTitle: "Comprehensive 5-Year Performance & O&M Guarantee",
        category: "TECHNICAL",
        mandatory: false,
        result: "REVIEW_REQUIRED",
        confidence: 0.79,
        explanation:
          "O&M clause excludes grid curtailment exceeding 24 hours per quarter. Officer signoff required to confirm grid exclusion allowance.",
        reviewStatus: "PENDING_REVIEW",
        nliResult: {
          status: "INSUFFICIENT",
          explanation: "NLI model flagged potential ambiguity in grid exclusion clause wording.",
          confidence: 0.81,
          modelVersion: "DeBERTa-v3-nli",
        },
        evidence: {
          _id: "ev-002-5",
          documentId: "doc-bid-002-tech",
          documentName: "Adani_Green_Technical_Proposal.pdf",
          requirementId: "req-005",
          bidId: "bid-002",
          pageNumber: 88,
          clauseReference: "O&M Guarantee Clause 12.2",
          extractedText: "PR guarantee 78% subject to grid curtailment exclusion threshold of 24 hours/quarter.",
          confidence: 0.79,
          boundingBox: { x: 50, y: 350, width: 500, height: 90 },
        },
      },
      {
        _id: "res-002-6",
        requirementId: "req-006",
        requirementTitle: "GST Registration & Active Portal Status",
        category: "ELIGIBILITY",
        mandatory: true,
        result: "REVIEW_REQUIRED",
        confidence: 0.82,
        explanation:
          "GSTIN 24AABCA4512E1Z2 verified; however, portal record displays 'Adani Green Energy Systems Ltd' while proposal lists 'Adani Green Energy Systems Limited'. Minor spelling mismatch requires officer confirmation.",
        reviewStatus: "PENDING_REVIEW",
        statutoryVerification: {
          portal: "GST",
          identifier: "24AABCA4512E1Z2",
          status: "MISMATCH",
          verifiedName: "ADANI GREEN ENERGY SYSTEMS LTD",
          matchedName: "ADANI GREEN ENERGY SYSTEMS LIMITED",
          isMatch: false,
          environment: "DEMO / SYNTHETIC VERIFICATION DATA",
          verifiedAt: "2026-03-01T15:02:00Z",
        },
        evidence: {
          _id: "ev-002-6",
          documentId: "doc-bid-002-statutory",
          documentName: "Statutory_Certificates_Adani.pdf",
          requirementId: "req-006",
          bidId: "bid-002",
          pageNumber: 2,
          clauseReference: "GST REG-06",
          extractedText: "GSTIN: 24AABCA4512E1Z2; Legal Name: ADANI GREEN ENERGY SYSTEMS LTD.",
          confidence: 0.82,
          boundingBox: { x: 50, y: 110, width: 490, height: 85 },
        },
      },
      {
        _id: "res-002-7",
        requirementId: "req-007",
        requirementTitle: "Permanent Account Number (PAN) Verification",
        category: "ELIGIBILITY",
        mandatory: true,
        result: "COMPLIANT",
        confidence: 0.98,
        explanation: "PAN AABCA4512E verified successfully.",
        reviewStatus: "VERIFIED",
        statutoryVerification: {
          portal: "PAN",
          identifier: "AABCA4512E",
          status: "VERIFIED",
          verifiedName: "ADANI GREEN ENERGY SYSTEMS LIMITED",
          matchedName: "ADANI GREEN ENERGY SYSTEMS LIMITED",
          isMatch: true,
          environment: "DEMO / SYNTHETIC VERIFICATION DATA",
          verifiedAt: "2026-03-01T15:02:10Z",
        },
        evidence: {
          _id: "ev-002-7",
          documentId: "doc-bid-002-statutory",
          documentName: "Statutory_Certificates_Adani.pdf",
          requirementId: "req-007",
          bidId: "bid-002",
          pageNumber: 4,
          clauseReference: "PAN Card Copy",
          extractedText: "PAN: AABCA4512E; Name: ADANI GREEN ENERGY SYSTEMS LIMITED.",
          confidence: 0.98,
          boundingBox: { x: 50, y: 190, width: 450, height: 75 },
        },
      },
      {
        _id: "res-002-8",
        requirementId: "req-008",
        requirementTitle: "Non-Blacklisting & Debarment Verification",
        category: "COMPLIANCE",
        mandatory: true,
        result: "COMPLIANT",
        confidence: 0.97,
        explanation: "No debarment records found on statutory portals.",
        reviewStatus: "VERIFIED",
        statutoryVerification: {
          portal: "DEBARMENT",
          identifier: "AABCA4512E",
          status: "VERIFIED",
          verifiedName: "Adani Green Energy Systems Ltd",
          matchedName: "Adani Green Energy Systems Ltd",
          isMatch: true,
          isDebarred: false,
          environment: "DEMO / SYNTHETIC VERIFICATION DATA",
          verifiedAt: "2026-03-01T15:02:15Z",
        },
        evidence: {
          _id: "ev-002-8",
          documentId: "doc-bid-002-statutory",
          documentName: "Statutory_Certificates_Adani.pdf",
          requirementId: "req-008",
          bidId: "bid-002",
          pageNumber: 8,
          clauseReference: "Debarment Affidavit",
          extractedText: "Self-declaration confirming no blacklisting or debarment.",
          confidence: 0.97,
          boundingBox: { x: 50, y: 260, width: 480, height: 70 },
        },
      },
      {
        _id: "res-002-9",
        requirementId: "req-009",
        requirementTitle: "OEM Authorization Letter for Key Components",
        category: "CERTIFICATION",
        mandatory: true,
        result: "COMPLIANT",
        confidence: 0.96,
        explanation: "OEM letter for inverters provided.",
        reviewStatus: "VERIFIED",
        evidence: {
          _id: "ev-002-9",
          documentId: "doc-bid-002-tech",
          documentName: "Adani_Green_Technical_Proposal.pdf",
          requirementId: "req-009",
          bidId: "bid-002",
          pageNumber: 95,
          clauseReference: "OEM Authorization Annexure",
          extractedText: "OEM Authorization Form MAF-2026-081.",
          confidence: 0.96,
          boundingBox: { x: 50, y: 310, width: 460, height: 70 },
        },
      },
      {
        _id: "res-002-10",
        requirementId: "req-010",
        requirementTitle: "Average Annual Audited Turnover Threshold",
        category: "FINANCIAL",
        mandatory: true,
        result: "COMPLIANT",
        confidence: 0.97,
        explanation: "Average 3-year turnover verified at INR 1,420 Crore.",
        reviewStatus: "VERIFIED",
        evidence: {
          _id: "ev-002-10",
          documentId: "doc-bid-002-tech",
          documentName: "Adani_Green_Technical_Proposal.pdf",
          requirementId: "req-010",
          bidId: "bid-002",
          pageNumber: 55,
          clauseReference: "Financial Summary",
          extractedText: "3-Year Average Financial Turnover: ₹1,420 Crore.",
          confidence: 0.97,
          boundingBox: { x: 50, y: 210, width: 470, height: 80 },
        },
      },
    ],
  },

  // BIDDER C: NON-COMPLIANT / HIGH RISK (Score: 48%)
  {
    _id: "cmp-003",
    tenderId: PRESENTATION_TENDER_ID,
    tenderTitle: presentationTender.title,
    bidId: "bid-003",
    vendorName: "Vertex Infotech & Power Solutions Pvt Ltd",
    score: 48,
    compliantCount: 4,
    reviewRequiredCount: 2,
    nonCompliantCount: 4,
    riskLevel: "HIGH",
    status: "REQUIRES_REVIEW",
    createdAt: "2026-03-02T14:30:00Z",
    results: [
      {
        _id: "res-003-1",
        requirementId: "req-001",
        requirementTitle: "Tier-1 Mono-PERC Solar Cell Minimum Efficiency",
        category: "TECHNICAL",
        mandatory: true,
        result: "COMPLIANT",
        confidence: 0.91,
        explanation: "Module efficiency declared at 21.5%.",
        reviewStatus: "VERIFIED",
        evidence: {
          _id: "ev-003-1",
          documentId: "doc-bid-003-tech",
          documentName: "Vertex_Proposal_Submissions.pdf",
          requirementId: "req-001",
          bidId: "bid-003",
          pageNumber: 12,
          clauseReference: "Specs Page 12",
          extractedText: "Mono-PERC efficiency: 21.5%.",
          confidence: 0.91,
          boundingBox: { x: 50, y: 120, width: 450, height: 60 },
        },
      },
      {
        _id: "res-003-2",
        requirementId: "req-002",
        requirementTitle: "Mandatory BIS & IEC Compliance Standards",
        category: "CERTIFICATION",
        mandatory: true,
        result: "REVIEW_REQUIRED",
        confidence: 0.71,
        explanation: "Submitted IEC lab test report expired in November 2024. Updated renewal pending officer check.",
        reviewStatus: "PENDING_REVIEW",
        evidence: {
          _id: "ev-003-2",
          documentId: "doc-bid-003-tech",
          documentName: "Vertex_Proposal_Submissions.pdf",
          requirementId: "req-002",
          bidId: "bid-003",
          pageNumber: 25,
          clauseReference: "IEC Test Report",
          extractedText: "IEC 61215 Certificate expiry date: 15-Nov-2024.",
          confidence: 0.71,
          boundingBox: { x: 50, y: 180, width: 480, height: 75 },
        },
      },
      {
        _id: "res-003-3",
        requirementId: "req-003",
        requirementTitle: "Minimum Net Worth and Working Capital Facility",
        category: "FINANCIAL",
        mandatory: true,
        result: "NON_COMPLIANT",
        confidence: 0.92,
        explanation:
          "Reported Net Worth of INR 52 Crore contradicted by MCA statutory filing showing Net Worth of INR 18.4 Crore (below mandatory INR 50 Cr threshold).",
        reviewStatus: "PENDING_REVIEW",
        ruleEvaluation: {
          rule: "NET_WORTH_MCA_CROSS_CHECK",
          extractedValue: "INR 18.4 Crore (MCA Verified)",
          thresholdValue: "INR 50 Crore",
          passed: false,
        },
        evidence: {
          _id: "ev-003-3",
          documentId: "doc-bid-003-tech",
          documentName: "Vertex_Proposal_Submissions.pdf",
          requirementId: "req-003",
          bidId: "bid-003",
          pageNumber: 42,
          clauseReference: "Balance Sheet Summary",
          extractedText: "Net worth calculated at INR 520 Million in self-audited draft.",
          confidence: 0.92,
          boundingBox: { x: 50, y: 240, width: 490, height: 80 },
        },
      },
      {
        _id: "res-003-4",
        requirementId: "req-004",
        requirementTitle: "Domestic Content Requirement (DCR) Compliance",
        category: "COMPLIANCE",
        mandatory: true,
        result: "NON_COMPLIANT",
        confidence: 0.95,
        explanation: "Cell origin declared imported from third country; fails 60% DCR local content threshold.",
        reviewStatus: "PENDING_REVIEW",
        nliResult: {
          status: "CONTRADICTS",
          explanation: "NLI model detected explicit declaration of imported solar cells violating DCR mandate.",
          confidence: 0.94,
          modelVersion: "DeBERTa-v3-nli",
        },
        evidence: {
          _id: "ev-003-4",
          documentId: "doc-bid-003-tech",
          documentName: "Vertex_Proposal_Submissions.pdf",
          requirementId: "req-004",
          bidId: "bid-003",
          pageNumber: 58,
          clauseReference: "Cell Supply Declaration",
          extractedText: "Solar cells sourced from overseas supplier Xiamen Tech (Imported). Local content: 34%.",
          confidence: 0.95,
          boundingBox: { x: 50, y: 310, width: 500, height: 85 },
        },
      },
      {
        _id: "res-003-5",
        requirementId: "req-005",
        requirementTitle: "Comprehensive 5-Year Performance & O&M Guarantee",
        category: "TECHNICAL",
        mandatory: false,
        result: "REVIEW_REQUIRED",
        confidence: 0.68,
        explanation: "No performance liquidated damages cap specified in O&M proposal.",
        reviewStatus: "PENDING_REVIEW",
        evidence: {
          _id: "ev-003-5",
          documentId: "doc-bid-003-tech",
          documentName: "Vertex_Proposal_Submissions.pdf",
          requirementId: "req-005",
          bidId: "bid-003",
          pageNumber: 64,
          clauseReference: "O&M Schedule",
          extractedText: "Standard O&M services provided for 3 years (Option for 5 years).",
          confidence: 0.68,
          boundingBox: { x: 50, y: 390, width: 470, height: 70 },
        },
      },
      {
        _id: "res-003-6",
        requirementId: "req-006",
        requirementTitle: "GST Registration & Active Portal Status",
        category: "ELIGIBILITY",
        mandatory: true,
        result: "COMPLIANT",
        confidence: 0.96,
        explanation: "GSTIN 07AAACV9012F1Z4 verified.",
        reviewStatus: "VERIFIED",
        statutoryVerification: {
          portal: "GST",
          identifier: "07AAACV9012F1Z4",
          status: "VERIFIED",
          verifiedName: "VERTEX INFOTECH & POWER SOLUTIONS PVT LTD",
          matchedName: "VERTEX INFOTECH & POWER SOLUTIONS PVT LTD",
          isMatch: true,
          environment: "DEMO / SYNTHETIC VERIFICATION DATA",
          verifiedAt: "2026-03-02T14:32:00Z",
        },
        evidence: {
          _id: "ev-003-6",
          documentId: "doc-bid-003-tech",
          documentName: "Vertex_Proposal_Submissions.pdf",
          requirementId: "req-006",
          bidId: "bid-003",
          pageNumber: 3,
          clauseReference: "GST Copy",
          extractedText: "GSTIN: 07AAACV9012F1Z4.",
          confidence: 0.96,
          boundingBox: { x: 50, y: 100, width: 440, height: 60 },
        },
      },
      {
        _id: "res-003-7",
        requirementId: "req-007",
        requirementTitle: "Permanent Account Number (PAN) Verification",
        category: "ELIGIBILITY",
        mandatory: true,
        result: "COMPLIANT",
        confidence: 0.96,
        explanation: "PAN AAACV9012F verified.",
        reviewStatus: "VERIFIED",
        statutoryVerification: {
          portal: "PAN",
          identifier: "AAACV9012F",
          status: "VERIFIED",
          verifiedName: "VERTEX INFOTECH & POWER SOLUTIONS PVT LTD",
          matchedName: "VERTEX INFOTECH & POWER SOLUTIONS PVT LTD",
          isMatch: true,
          environment: "DEMO / SYNTHETIC VERIFICATION DATA",
          verifiedAt: "2026-03-02T14:32:05Z",
        },
        evidence: {
          _id: "ev-003-7",
          documentId: "doc-bid-003-tech",
          documentName: "Vertex_Proposal_Submissions.pdf",
          requirementId: "req-007",
          bidId: "bid-003",
          pageNumber: 5,
          clauseReference: "PAN Copy",
          extractedText: "PAN: AAACV9012F.",
          confidence: 0.96,
          boundingBox: { x: 50, y: 140, width: 430, height: 60 },
        },
      },
      {
        _id: "res-003-8",
        requirementId: "req-008",
        requirementTitle: "Non-Blacklisting & Debarment Verification",
        category: "COMPLIANCE",
        mandatory: true,
        result: "NON_COMPLIANT",
        confidence: 0.94,
        explanation: "Adverse verification record: State Electricity Board debarment order issued in Oct 2025.",
        reviewStatus: "PENDING_REVIEW",
        statutoryVerification: {
          portal: "DEBARMENT",
          identifier: "AAACV9012F",
          status: "NON_COMPLIANT",
          verifiedName: "Vertex Infotech & Power Solutions Pvt Ltd",
          matchedName: "Vertex Infotech & Power Solutions Pvt Ltd",
          isMatch: true,
          isDebarred: true,
          environment: "DEMO / SYNTHETIC VERIFICATION DATA",
          verifiedAt: "2026-03-02T14:32:10Z",
        },
        evidence: {
          _id: "ev-003-8",
          documentId: "doc-bid-003-tech",
          documentName: "Vertex_Proposal_Submissions.pdf",
          requirementId: "req-008",
          bidId: "bid-003",
          pageNumber: 80,
          clauseReference: "Affidavit Section",
          extractedText: "Vendor declaration omits mention of SEB 2025 debarment notice.",
          confidence: 0.94,
          boundingBox: { x: 50, y: 450, width: 490, height: 80 },
        },
      },
      {
        _id: "res-003-9",
        requirementId: "req-009",
        requirementTitle: "OEM Authorization Letter for Key Components",
        category: "CERTIFICATION",
        mandatory: true,
        result: "NON_COMPLIANT",
        confidence: 0.98,
        explanation: "Mandatory OEM Authorization letter for central string inverters is missing from proposal documents.",
        reviewStatus: "PENDING_REVIEW",
        evidence: {
          _id: "ev-003-9",
          documentId: "doc-bid-003-tech",
          documentName: "Vertex_Proposal_Submissions.pdf",
          requirementId: "req-009",
          bidId: "bid-003",
          pageNumber: 90,
          clauseReference: "Missing OEM Letter",
          extractedText: "NO OEM AUTHORIZATION ATTACHED FOR INVERTER SPECIFICATIONS.",
          confidence: 0.98,
          boundingBox: { x: 50, y: 520, width: 500, height: 80 },
        },
      },
      {
        _id: "res-003-10",
        requirementId: "req-010",
        requirementTitle: "Average Annual Audited Turnover Threshold",
        category: "FINANCIAL",
        mandatory: true,
        result: "NON_COMPLIANT",
        confidence: 0.96,
        explanation: "Average 3-year turnover verified at INR 42 Crore against mandatory threshold of INR 150 Crore.",
        reviewStatus: "PENDING_REVIEW",
        ruleEvaluation: {
          rule: "TURNOVER_THRESHOLD_CHECK",
          extractedValue: "INR 42 Crore",
          thresholdValue: "INR 150 Crore",
          passed: false,
        },
        evidence: {
          _id: "ev-003-10",
          documentId: "doc-bid-003-tech",
          documentName: "Vertex_Proposal_Submissions.pdf",
          requirementId: "req-010",
          bidId: "bid-003",
          pageNumber: 45,
          clauseReference: "CA Financial Statement",
          extractedText: "FY 2022-23: ₹38 Cr; FY 2023-24: ₹42 Cr; FY 2024-25: ₹46 Cr. Average: ₹42 Cr.",
          confidence: 0.96,
          boundingBox: { x: 50, y: 280, width: 480, height: 90 },
        },
      },
    ],
  },

  // BIDDER D: REVIEW REQUIRED / MEDIUM RISK (Score: 78%)
  {
    _id: "cmp-004",
    tenderId: PRESENTATION_TENDER_ID,
    tenderTitle: presentationTender.title,
    bidId: "bid-004",
    vendorName: "Evergreen Energy Private Limited",
    score: 78,
    compliantCount: 8,
    reviewRequiredCount: 2,
    nonCompliantCount: 0,
    riskLevel: "MEDIUM",
    status: "REQUIRES_REVIEW",
    createdAt: "2026-03-03T16:15:00Z",
    results: [
      {
        _id: "res-004-1",
        requirementId: "req-001",
        requirementTitle: "Tier-1 Mono-PERC Solar Cell Minimum Efficiency",
        category: "TECHNICAL",
        mandatory: true,
        result: "COMPLIANT",
        confidence: 0.96,
        explanation: "Mono-PERC efficiency verified at 21.7%.",
        reviewStatus: "VERIFIED",
        evidence: {
          _id: "ev-004-1",
          documentId: "doc-bid-004-tech",
          documentName: "Evergreen_Energy_Proposal.pdf",
          requirementId: "req-001",
          bidId: "bid-004",
          pageNumber: 15,
          clauseReference: "Technical Data Sheet",
          extractedText: "Module efficiency: 21.7%.",
          confidence: 0.96,
          boundingBox: { x: 50, y: 130, width: 460, height: 70 },
        },
      },
      {
        _id: "res-004-2",
        requirementId: "req-002",
        requirementTitle: "Mandatory BIS & IEC Compliance Standards",
        category: "CERTIFICATION",
        mandatory: true,
        result: "COMPLIANT",
        confidence: 0.95,
        explanation: "Valid BIS R-41005531 certificate verified.",
        reviewStatus: "VERIFIED",
        evidence: {
          _id: "ev-004-2",
          documentId: "doc-bid-004-tech",
          documentName: "Evergreen_Energy_Proposal.pdf",
          requirementId: "req-002",
          bidId: "bid-004",
          pageNumber: 22,
          clauseReference: "BIS Copy",
          extractedText: "BIS Registration R-41005531.",
          confidence: 0.95,
          boundingBox: { x: 50, y: 190, width: 450, height: 60 },
        },
      },
      {
        _id: "res-004-3",
        requirementId: "req-003",
        requirementTitle: "Minimum Net Worth and Working Capital Facility",
        category: "FINANCIAL",
        mandatory: true,
        result: "COMPLIANT",
        confidence: 0.94,
        explanation: "Net worth verified at INR 54 Crore.",
        reviewStatus: "VERIFIED",
        evidence: {
          _id: "ev-004-3",
          documentId: "doc-bid-004-tech",
          documentName: "Evergreen_Energy_Proposal.pdf",
          requirementId: "req-003",
          bidId: "bid-004",
          pageNumber: 38,
          clauseReference: "Net Worth Certificate",
          extractedText: "Net worth: INR 540 Million.",
          confidence: 0.94,
          boundingBox: { x: 50, y: 250, width: 470, height: 70 },
        },
      },
      {
        _id: "res-004-4",
        requirementId: "req-004",
        requirementTitle: "Domestic Content Requirement (DCR) Compliance",
        category: "COMPLIANCE",
        mandatory: true,
        result: "COMPLIANT",
        confidence: 0.92,
        explanation: "Local content 62% declared.",
        reviewStatus: "VERIFIED",
        evidence: {
          _id: "ev-004-4",
          documentId: "doc-bid-004-tech",
          documentName: "Evergreen_Energy_Proposal.pdf",
          requirementId: "req-004",
          bidId: "bid-004",
          pageNumber: 45,
          clauseReference: "DCR Declaration",
          extractedText: "Local domestic content: 62%.",
          confidence: 0.92,
          boundingBox: { x: 50, y: 310, width: 460, height: 60 },
        },
      },
      {
        _id: "res-004-5",
        requirementId: "req-005",
        requirementTitle: "Comprehensive 5-Year Performance & O&M Guarantee",
        category: "TECHNICAL",
        mandatory: false,
        result: "REVIEW_REQUIRED",
        confidence: 0.77,
        explanation: "O&M team size commitment requires officer clarification.",
        reviewStatus: "PENDING_REVIEW",
        evidence: {
          _id: "ev-004-5",
          documentId: "doc-bid-004-tech",
          documentName: "Evergreen_Energy_Proposal.pdf",
          requirementId: "req-004-5",
          bidId: "bid-004",
          pageNumber: 52,
          clauseReference: "O&M Personnel",
          extractedText: "O&M dedicated team of 12 personnel assigned.",
          confidence: 0.77,
          boundingBox: { x: 50, y: 370, width: 480, height: 70 },
        },
      },
      {
        _id: "res-004-6",
        requirementId: "req-006",
        requirementTitle: "GST Registration & Active Portal Status",
        category: "ELIGIBILITY",
        mandatory: true,
        result: "COMPLIANT",
        confidence: 0.98,
        explanation: "GSTIN 09AAACE5512B1Z8 verified.",
        reviewStatus: "VERIFIED",
        statutoryVerification: {
          portal: "GST",
          identifier: "09AAACE5512B1Z8",
          status: "VERIFIED",
          verifiedName: "EVERGREEN ENERGY PRIVATE LIMITED",
          matchedName: "EVERGREEN ENERGY PRIVATE LIMITED",
          isMatch: true,
          environment: "DEMO / SYNTHETIC VERIFICATION DATA",
          verifiedAt: "2026-03-03T16:16:00Z",
        },
        evidence: {
          _id: "ev-004-6",
          documentId: "doc-bid-004-tech",
          documentName: "Evergreen_Energy_Proposal.pdf",
          requirementId: "req-006",
          bidId: "bid-004",
          pageNumber: 4,
          clauseReference: "GST Document",
          extractedText: "GSTIN: 09AAACE5512B1Z8.",
          confidence: 0.98,
          boundingBox: { x: 50, y: 110, width: 440, height: 60 },
        },
      },
      {
        _id: "res-004-7",
        requirementId: "req-007",
        requirementTitle: "Permanent Account Number (PAN) Verification",
        category: "ELIGIBILITY",
        mandatory: true,
        result: "COMPLIANT",
        confidence: 0.98,
        explanation: "PAN AAACE5512B verified.",
        reviewStatus: "VERIFIED",
        statutoryVerification: {
          portal: "PAN",
          identifier: "AAACE5512B",
          status: "VERIFIED",
          verifiedName: "EVERGREEN ENERGY PRIVATE LIMITED",
          matchedName: "EVERGREEN ENERGY PRIVATE LIMITED",
          isMatch: true,
          environment: "DEMO / SYNTHETIC VERIFICATION DATA",
          verifiedAt: "2026-03-03T16:16:05Z",
        },
        evidence: {
          _id: "ev-004-7",
          documentId: "doc-bid-004-tech",
          documentName: "Evergreen_Energy_Proposal.pdf",
          requirementId: "req-007",
          bidId: "bid-004",
          pageNumber: 6,
          clauseReference: "PAN Copy",
          extractedText: "PAN: AAACE5512B.",
          confidence: 0.98,
          boundingBox: { x: 50, y: 150, width: 430, height: 60 },
        },
      },
      {
        _id: "res-004-8",
        requirementId: "req-008",
        requirementTitle: "Non-Blacklisting & Debarment Verification",
        category: "COMPLIANCE",
        mandatory: true,
        result: "COMPLIANT",
        confidence: 0.97,
        explanation: "No debarment records found.",
        reviewStatus: "VERIFIED",
        statutoryVerification: {
          portal: "DEBARMENT",
          identifier: "AAACE5512B",
          status: "VERIFIED",
          verifiedName: "Evergreen Energy Private Limited",
          matchedName: "Evergreen Energy Private Limited",
          isMatch: true,
          isDebarred: false,
          environment: "DEMO / SYNTHETIC VERIFICATION DATA",
          verifiedAt: "2026-03-03T16:16:10Z",
        },
        evidence: {
          _id: "ev-004-8",
          documentId: "doc-bid-004-tech",
          documentName: "Evergreen_Energy_Proposal.pdf",
          requirementId: "req-008",
          bidId: "bid-004",
          pageNumber: 60,
          clauseReference: "Debarment Affidavit",
          extractedText: "Affidavit confirming clean debarment status.",
          confidence: 0.97,
          boundingBox: { x: 50, y: 410, width: 480, height: 70 },
        },
      },
      {
        _id: "res-004-9",
        requirementId: "req-009",
        requirementTitle: "OEM Authorization Letter for Key Components",
        category: "CERTIFICATION",
        mandatory: true,
        result: "COMPLIANT",
        confidence: 0.95,
        explanation: "Valid OEM letter provided.",
        reviewStatus: "VERIFIED",
        evidence: {
          _id: "ev-004-9",
          documentId: "doc-bid-004-tech",
          documentName: "Evergreen_Energy_Proposal.pdf",
          requirementId: "req-009",
          bidId: "bid-004",
          pageNumber: 68,
          clauseReference: "OEM Form",
          extractedText: "OEM Authorization letter attached.",
          confidence: 0.95,
          boundingBox: { x: 50, y: 470, width: 460, height: 60 },
        },
      },
      {
        _id: "res-004-10",
        requirementId: "req-010",
        requirementTitle: "Average Annual Audited Turnover Threshold",
        category: "FINANCIAL",
        mandatory: true,
        result: "REVIEW_REQUIRED",
        confidence: 0.81,
        explanation:
          "Average 3-year turnover verified at INR 152 Crore (barely exceeding mandatory INR 150 Crore threshold). Financial officer signoff required.",
        reviewStatus: "PENDING_REVIEW",
        ruleEvaluation: {
          rule: "TURNOVER_THRESHOLD_CHECK",
          extractedValue: "INR 152 Crore",
          thresholdValue: "INR 150 Crore",
          passed: true,
        },
        evidence: {
          _id: "ev-004-10",
          documentId: "doc-bid-004-tech",
          documentName: "Evergreen_Energy_Proposal.pdf",
          requirementId: "req-010",
          bidId: "bid-004",
          pageNumber: 32,
          clauseReference: "Financials Page 32",
          extractedText: "FY 2022-23: ₹148 Cr; FY 2023-24: ₹152 Cr; FY 2024-25: ₹156 Cr. 3-Year Avg: ₹152 Cr.",
          confidence: 0.81,
          boundingBox: { x: 50, y: 210, width: 490, height: 85 },
        },
      },
    ],
  },
];

// ----------------------------------------------------
// RISK ASSESSMENTS FOR ALL 4 BIDDERS
// ----------------------------------------------------

export const presentationRiskAssessments: RiskAssessment[] = [
  {
    _id: "rsk-001",
    bidId: "bid-001",
    vendorName: "Tata Power Renewable Energy Limited",
    tenderTitle: presentationTender.title,
    complianceAnalysisId: "cmp-001",
    level: "LOW",
    score: 4,
    engineVersion: "v2.4.0-xgb",
    explanation:
      "Low composite risk profile. All 10 mandatory eligibility, technical, financial, and certification rules are compliant with high confidence (92-99%). Zero statutory discrepancies detected.",
    signals: [],
    createdAt: "2026-03-01T14:32:00Z",
  },
  {
    _id: "rsk-002",
    bidId: "bid-002",
    vendorName: "Adani Green Energy Systems Ltd",
    tenderTitle: presentationTender.title,
    complianceAnalysisId: "cmp-002",
    level: "MEDIUM",
    score: 18,
    engineVersion: "v2.4.0-xgb",
    explanation:
      "Medium risk profile. Identified a minor legal entity name spelling variance in GST portal records and O&M grid curtailment clause requiring procurement officer review.",
    signals: [
      {
        id: "sig-002-1",
        type: "DISCREPANCY",
        severity: "MEDIUM",
        description: "GST portal trade name 'Adani Green Energy Systems Ltd' differs slightly from proposal 'Adani Green Energy Systems Limited'.",
        affectedRequirementId: "req-006",
      },
      {
        id: "sig-002-2",
        type: "MARGINAL_COMPLIANCE",
        severity: "LOW",
        description: "O&M grid curtailment exclusion hours slightly exceed standard tender template threshold.",
        affectedRequirementId: "req-005",
      },
    ],
    createdAt: "2026-03-01T15:05:00Z",
  },
  {
    _id: "rsk-003",
    bidId: "bid-003",
    vendorName: "Vertex Infotech & Power Solutions Pvt Ltd",
    tenderTitle: presentationTender.title,
    complianceAnalysisId: "cmp-003",
    level: "HIGH",
    score: 52,
    engineVersion: "v2.4.0-xgb",
    explanation:
      "High risk profile. Disqualified due to multiple failed mandatory criteria including missing OEM authorization, failed DCR domestic content, financial turnover shortfall (₹42 Cr vs ₹150 Cr threshold), and MCA net worth discrepancy.",
    signals: [
      {
        id: "sig-003-1",
        type: "MISSING_EVIDENCE",
        severity: "HIGH",
        description: "Mandatory OEM Authorization Letter for central string inverters is completely missing.",
        affectedRequirementId: "req-009",
      },
      {
        id: "sig-003-2",
        type: "ANOMALY",
        severity: "HIGH",
        description: "Reported net worth of ₹52 Cr contradicted by MCA statutory filings showing ₹18.4 Cr.",
        affectedRequirementId: "req-003",
      },
      {
        id: "sig-003-3",
        type: "DISCREPANCY",
        severity: "HIGH",
        description: "Solar cells declared imported from third country violating 60% DCR mandate.",
        affectedRequirementId: "req-004",
      },
    ],
    createdAt: "2026-03-02T14:35:00Z",
  },
  {
    _id: "rsk-004",
    bidId: "bid-004",
    vendorName: "Evergreen Energy Private Limited",
    tenderTitle: presentationTender.title,
    complianceAnalysisId: "cmp-004",
    level: "MEDIUM",
    score: 22,
    engineVersion: "v2.4.0-xgb",
    explanation:
      "Medium risk profile. Financial turnover of ₹152 Crore barely satisfies the ₹150 Crore eligibility threshold, requiring financial officer verification.",
    signals: [
      {
        id: "sig-004-1",
        type: "MARGINAL_COMPLIANCE",
        severity: "MEDIUM",
        description: "Turnover of ₹152 Crore is within 1.5% of mandatory eligibility threshold.",
        affectedRequirementId: "req-010",
      },
    ],
    createdAt: "2026-03-03T16:20:00Z",
  },
];

// ----------------------------------------------------
// DOCUMENT REGISTRY FOR KNOWN PRESENTATION DOCUMENTS
// ----------------------------------------------------

export interface KnownPresentationDocument {
  documentId: string;
  fileName: string;
  sha256?: string;
  documentType: string;
  bidderId: string;
  vendorName: string;
  requirementIds: string[];
  verificationProvider?: "GST" | "PAN" | "UDYAM" | "MCA" | "BIS" | "DEBARMENT";
  extractedText: string;
  structuredFields: { key: string; label: string; value: string; confidence: number }[];
}

export const PRESENTATION_DOCUMENT_REGISTRY: KnownPresentationDocument[] = [
  {
    documentId: "doc-bid-001-gst",
    fileName: "GST_Certificate_Pragati.pdf",
    sha256: "gst-pragati-07wkmcp4023i9zy-sha256-hash-001",
    documentType: "GST_CERTIFICATE",
    bidderId: "bid-001",
    vendorName: "Pragati Micro Control Systems Proprietorship",
    requirementIds: ["req-006"],
    verificationProvider: "GST",
    extractedText:
      "GOVERNMENT OF INDIA - GOODS AND SERVICES TAX REGISTRATION CERTIFICATE. Registration Number: 07WKMCP4023I9ZY. Legal Name: Pragati Micro Control Systems Proprietorship. Trade Name: Pragati Micro Control Systems. Date of Liability: 04/07/2017. Type of Registration: Regular.",
    structuredFields: [
      { key: "GSTIN", label: "GSTIN Number", value: "07WKMCP4023I9ZY", confidence: 0.99 },
      { key: "LEGAL_NAME", label: "Legal Name", value: "Pragati Micro Control Systems Proprietorship", confidence: 0.99 },
      { key: "STATUS", label: "Registration Status", value: "ACTIVE", confidence: 0.99 },
    ],
  },
  {
    documentId: "doc-bid-001-pan",
    fileName: "PAN_Card_Pragati.pdf",
    sha256: "pan-pragati-wkmcp4023i-sha256-hash-002",
    documentType: "PAN_CARD",
    bidderId: "bid-001",
    vendorName: "Pragati Micro Control Systems Proprietorship",
    requirementIds: ["req-007"],
    verificationProvider: "PAN",
    extractedText:
      "INCOME TAX DEPARTMENT - GOVT OF INDIA. Permanent Account Number: WKMCP4023I. Name: Pragati Micro Control Systems Proprietorship. Date of Incorporation: 04/07/2017. Category: Proprietorship Concern.",
    structuredFields: [
      { key: "PAN", label: "PAN Number", value: "WKMCP4023I", confidence: 0.99 },
      { key: "NAME", label: "Entity Name", value: "Pragati Micro Control Systems Proprietorship", confidence: 0.99 },
    ],
  },
  {
    documentId: "doc-bid-001-tech",
    fileName: "Pragati_Technical_Proposal_Vol_I.pdf",
    sha256: "tech-pragati-500mw-solar-proposal-sha256-003",
    documentType: "TECHNICAL_PROPOSAL",
    bidderId: "bid-001",
    vendorName: "Pragati Micro Control Systems Proprietorship",
    requirementIds: ["req-001", "req-002", "req-004", "req-005", "req-008"],
    verificationProvider: "BIS",
    extractedText:
      "PRAGATI MICRO CONTROL SYSTEMS PROPRIETORSHIP TECHNICAL BID PROPOSAL. 500MW Grid Connected Solar PV Plant. Module Efficiency: 21.8% Mono-PERC Bifacial Modules. BIS Registration: R-41000921 under IS 14286 / IEC 61215. Domestic Content: 100% cell line manufactured domestically. O&M Guarantee: 78.5% PR over 5 years. Non-blacklisting affidavit attached.",
    structuredFields: [
      { key: "EFFICIENCY", label: "Solar Cell Efficiency", value: "21.8%", confidence: 0.98 },
      { key: "BIS_NUMBER", label: "BIS Registration", value: "R-41000921", confidence: 0.96 },
      { key: "LOCAL_CONTENT", label: "Domestic Content (DCR)", value: "100%", confidence: 0.94 },
    ],
  },
  {
    documentId: "doc-bid-001-fin",
    fileName: "Audited_Financial_Statements_Pragati.pdf",
    sha256: "fin-pragati-ca-audited-turnover-sha256-004",
    documentType: "AUDITED_FINANCIALS",
    bidderId: "bid-001",
    vendorName: "Pragati Micro Control Systems Proprietorship",
    requirementIds: ["req-003", "req-010"],
    verificationProvider: "MCA",
    extractedText:
      "STATUTORY AUDITOR CERTIFICATE & AUDITED BALANCE SHEETS. Net Worth as on 31-Mar-2025: INR 4,128.4 Million. Sanctioned Working Capital Credit Limit: INR 750 Million (SBI). Annual Turnover FY 22-23: INR 1,650 Million, FY 23-24: INR 1,890 Million, FY 24-25: INR 1,980 Million. 3-Year Average: INR 1,840 Million.",
    structuredFields: [
      { key: "NET_WORTH", label: "Verified Net Worth", value: "₹412.84 Crore", confidence: 0.98 },
      { key: "AVG_TURNOVER", label: "3-Year Average Turnover", value: "₹1,840 Crore", confidence: 0.98 },
      { key: "WORKING_CAPITAL", label: "Sanctioned WC Limit", value: "₹75 Crore", confidence: 0.95 },
    ],
  },
  {
    documentId: "doc-bid-001-oem",
    fileName: "OEM_Authorization_Letter_Pragati.pdf",
    sha256: "oem-pragati-maf-letter-sha256-005",
    documentType: "OEM_AUTHORIZATION",
    bidderId: "bid-001",
    vendorName: "Pragati Micro Control Systems Proprietorship",
    requirementIds: ["req-009"],
    extractedText:
      "MANUFACTURER AUTHORIZATION FORM (MAF). To MNRE / GeM Procurement Authority. We hereby authorize M/s Pragati Micro Control Systems Proprietorship to bid and supply utility-scale solar central string inverters and solar PV modules.",
    structuredFields: [
      { key: "OEM_NAME", label: "OEM Manufacturer", value: "SolarTech India Systems / Partner Tier-1", confidence: 0.97 },
      { key: "AUTHORIZATION_STATUS", label: "MAF Status", value: "VALID & EXCLUSIVE", confidence: 0.97 },
    ],
  },
  // -----------------------------------------------------------------
  // GENERATED PRESENTATION DEMO PDFS (5 CORRECT / 5 WRONG)
  // GENERATED VIA BACKEND PDF_ENGINE & MONGODB ATLAS REAL DATA
  // -----------------------------------------------------------------
  {
    documentId: "doc-gen-01",
    fileName: "01_GST_Certificate_Valid.pdf",
    sha256: "224ed500c6b144449fc670dc3dccee80554d61d2b439b22523d294f51a901752",
    documentType: "GST_CERTIFICATE",
    bidderId: "SYN-BDR-000001",
    vendorName: "Pragati Micro Control Systems Proprietorship",
    requirementIds: ["req-006"],
    verificationProvider: "GST",
    extractedText:
      "GOVERNMENT OF INDIA — GOODS AND SERVICES TAX REGISTRATION CERTIFICATE (FORM GST REG-06). Registration Number (GSTIN): 07WKMCP4023I9ZY. Legal Name: Pragati Micro Control Systems Proprietorship. Trade Name: Pragati Micro Control Systems. Date of Liability: 04/07/2017. Registration Status: ACTIVE / OPERATIVE.",
    structuredFields: [
      { key: "GSTIN", label: "GSTIN Number", value: "07WKMCP4023I9ZY", confidence: 0.99 },
      { key: "LEGAL_NAME", label: "Legal Name", value: "Pragati Micro Control Systems Proprietorship", confidence: 0.99 },
      { key: "STATUS", label: "Registration Status", value: "ACTIVE", confidence: 0.99 },
    ],
  },
  {
    documentId: "doc-gen-02",
    fileName: "02_PAN_Card_Valid.pdf",
    sha256: "5710e9e52e3a84027996b493e78fd92d1007c1d20edeb11ecee6420dee29fa0e",
    documentType: "PAN_CARD",
    bidderId: "SYN-BDR-000001",
    vendorName: "Pragati Micro Control Systems Proprietorship",
    requirementIds: ["req-007"],
    verificationProvider: "PAN",
    extractedText:
      "INCOME TAX DEPARTMENT — GOVERNMENT OF INDIA. Permanent Account Number (PAN): WKMCP4023I. Name of Holder: Pragati Micro Control Systems Proprietorship. Category: Proprietorship Concern. Incorporation: 04/07/2017. Status: VERIFIED & ACTIVE IN ITD DATABASE.",
    structuredFields: [
      { key: "PAN", label: "PAN Number", value: "WKMCP4023I", confidence: 0.99 },
      { key: "NAME", label: "Entity Name", value: "Pragati Micro Control Systems Proprietorship", confidence: 0.99 },
    ],
  },
  {
    documentId: "doc-gen-03",
    fileName: "03_CA_Turnover_Certificate_Valid.pdf",
    sha256: "561edc3a9b76f16b9d70347e3d3a44a9c46472d0b28e00c3c75e09769f27dc89",
    documentType: "AUDITED_FINANCIALS",
    bidderId: "SYN-BDR-000001",
    vendorName: "Pragati Micro Control Systems Proprietorship",
    requirementIds: ["req-003", "req-010"],
    verificationProvider: "MCA",
    extractedText:
      "CHARTERED ACCOUNTANTS STATUTORY FINANCIAL CERTIFICATE. Audited Net Worth as on 31-Mar-2025: INR 412.84 Crore. FY 22-23: INR 165 Cr, FY 23-24: INR 189 Cr, FY 24-25: INR 198 Cr. 3-Year Average Turnover: INR 184.00 Crore. Sanctioned Working Capital Credit Line: INR 75.00 Crore (SBI).",
    structuredFields: [
      { key: "NET_WORTH", label: "Verified Net Worth", value: "₹412.84 Crore", confidence: 0.98 },
      { key: "AVG_TURNOVER", label: "3-Year Average Turnover", value: "₹184.00 Crore", confidence: 0.98 },
      { key: "WORKING_CAPITAL", label: "Sanctioned WC Limit", value: "₹75.00 Crore", confidence: 0.95 },
    ],
  },
  {
    documentId: "doc-gen-04",
    fileName: "04_Technical_Spec_MonoPERC_Valid.pdf",
    sha256: "5394b4677d714985aa7019071523078a3f5ebfd6d408a962fe0b904d167001af",
    documentType: "TECHNICAL_PROPOSAL",
    bidderId: "SYN-BDR-000001",
    vendorName: "Pragati Micro Control Systems Proprietorship",
    requirementIds: ["req-001", "req-002", "req-004"],
    verificationProvider: "BIS",
    extractedText:
      "TECHNICAL SPECIFICATION & COMPLIANCE DATASHEET. Solar Cell Tech: Tier-1 Mono-PERC Bifacial. Module Efficiency (STC): 21.80%. BIS Registration Number: R-41000921 under IS 14286 / IEC 61215:2021. Domestic Content (DCR): 100% Cell Line (Delhi NCR). Evaluation: COMPLIANT.",
    structuredFields: [
      { key: "EFFICIENCY", label: "Solar Cell Efficiency", value: "21.80%", confidence: 0.98 },
      { key: "BIS_NUMBER", label: "BIS Registration", value: "R-41000921", confidence: 0.96 },
      { key: "LOCAL_CONTENT", label: "Domestic Content (DCR)", value: "100%", confidence: 0.94 },
    ],
  },
  {
    documentId: "doc-gen-05",
    fileName: "05_OEM_Authorization_Letter_Valid.pdf",
    sha256: "2972c4f6c1779d42c4717e4ed5378d1c08ad3a661984fc115f7852905b4f94b0",
    documentType: "OEM_AUTHORIZATION",
    bidderId: "SYN-BDR-000001",
    vendorName: "Pragati Micro Control Systems Proprietorship",
    requirementIds: ["req-009"],
    extractedText:
      "MANUFACTURER AUTHORIZATION FORM (MAF). OEM Manufacturer: SolarTech India Systems Limited. Authorized System Integrator: Pragati Micro Control Systems Proprietorship. Tender: TND-2026-MNRE-0842. Warranty: Full 5-Year Comprehensive Warranty and Technical Support Guaranteed.",
    structuredFields: [
      { key: "OEM_NAME", label: "OEM Manufacturer", value: "SolarTech India Systems Limited", confidence: 0.97 },
      { key: "AUTHORIZATION_STATUS", label: "MAF Status", value: "VALID & AUTHORIZED", confidence: 0.97 },
    ],
  },
  {
    documentId: "doc-gen-06",
    fileName: "06_GST_Certificate_Mismatched_Name.pdf",
    sha256: "f7656793168e5d45306399328d149ba934d9393ed16719ba29e27d1139da96cf",
    documentType: "GST_CERTIFICATE",
    bidderId: "SYN-BDR-000002",
    vendorName: "Narmada Industrial Technologies Private Limited",
    requirementIds: ["req-006"],
    verificationProvider: "GST",
    extractedText:
      "GOVERNMENT OF INDIA — GOODS AND SERVICES TAX REGISTRATION CERTIFICATE. Registration Number (GSTIN): 19TZHCN2302A8ZX. Portal Registered Legal Name: NARMADA INDUSTRIAL TECH PVT LTD. Proposal Declared Name: Narmada Industrial Technologies Private Limited. Discrepancy Status: NAME VARIANCE DETECTED ('TECH PVT LTD' vs 'TECHNOLOGIES PRIVATE LIMITED').",
    structuredFields: [
      { key: "GSTIN", label: "GSTIN Number", value: "19TZHCN2302A8ZX", confidence: 0.98 },
      { key: "LEGAL_NAME", label: "Portal Registered Name", value: "NARMADA INDUSTRIAL TECH PVT LTD", confidence: 0.82 },
      { key: "DISCREPANCY", label: "Discrepancy Signal", value: "NAME VARIANCE DETECTED", confidence: 0.82 },
    ],
  },
  {
    documentId: "doc-gen-07",
    fileName: "07_CA_Turnover_Shortfall_Discrepancy.pdf",
    sha256: "6d28e1084f8e70e41100decbc210f4a13203e15619e3add65d78e5941ede0caf",
    documentType: "AUDITED_FINANCIALS",
    bidderId: "SYN-BDR-000009",
    vendorName: "Vertex Matrix Instrumentation Partnership",
    requirementIds: ["req-003", "req-010"],
    verificationProvider: "MCA",
    extractedText:
      "CHARTERED ACCOUNTANTS STATUTORY FINANCIAL CERTIFICATE — Vertex Matrix Instrumentation Partnership. Self-Reported Net Worth in Bid: INR 52.00 Crore (Draft). Verified MCA Net Worth (31-Mar-2025): INR 18.40 Crore (FAILED: Below mandatory INR 50 Cr threshold). 3-Year Average Financial Turnover: INR 42.00 Crore (FAILED: Below mandatory INR 150 Cr threshold).",
    structuredFields: [
      { key: "NET_WORTH", label: "Verified MCA Net Worth", value: "₹18.40 Crore (FAILED)", confidence: 0.92 },
      { key: "AVG_TURNOVER", label: "3-Year Average Turnover", value: "₹42.00 Crore (FAILED)", confidence: 0.96 },
    ],
  },
  {
    documentId: "doc-gen-08",
    fileName: "08_Technical_Spec_Expired_IEC_Certificate.pdf",
    sha256: "bb3c2387bebbfcbaf24eb67481ced422e80f7800dceadf4a2d21a412a706593c",
    documentType: "TECHNICAL_PROPOSAL",
    bidderId: "SYN-BDR-000009",
    vendorName: "Vertex Matrix Instrumentation Partnership",
    requirementIds: ["req-002"],
    extractedText:
      "INTERNATIONAL ELECTROTECHNICAL COMMISSION (IEC) TEST CERTIFICATE. Manufacturer: Vertex Matrix Instrumentation Partnership. Standard: IEC 61215:2005 / IEC 61730-1:2004. Certificate Number: IEC-CERT-2019-9012. Issue Date: 16-Nov-2019. Expiry Date: 15-Nov-2024 (EXPIRED 15 MONTHS AGO). Status: EXPIRED — RENEWAL NOT SUBMITTED.",
    structuredFields: [
      { key: "IEC_NUMBER", label: "IEC Certificate Ref", value: "IEC-CERT-2019-9012", confidence: 0.91 },
      { key: "EXPIRY_DATE", label: "Certificate Expiry Date", value: "15-Nov-2024 (EXPIRED)", confidence: 0.71 },
    ],
  },
  {
    documentId: "doc-gen-09",
    fileName: "09_Imported_Cell_DCR_Violation.pdf",
    sha256: "c3cc165bdb9c981fd5a4749ec080d7d8e2e1a262fcd9708af353ab3bb969f6b3",
    documentType: "TECHNICAL_PROPOSAL",
    bidderId: "SYN-BDR-000009",
    vendorName: "Vertex Matrix Instrumentation Partnership",
    requirementIds: ["req-004"],
    extractedText:
      "DOMESTIC CONTENT REQUIREMENT (DCR) DECLARATION. Solar Cells: China (Imported) from Xiamen Photovoltaic Tech Corp — DCR Local Content: 0.00%. Total Calculated Domestic Content: 34.00% (FAIL). Mandatory DCR Norm Threshold: >= 60.00%. Status: NON-COMPLIANT DCR VIOLATION.",
    structuredFields: [
      { key: "CELL_ORIGIN", label: "Solar Cell Origin", value: "China (Imported)", confidence: 0.95 },
      { key: "LOCAL_CONTENT", label: "Calculated Domestic Content", value: "34.00% (FAIL)", confidence: 0.95 },
    ],
  },
  {
    documentId: "doc-gen-10",
    fileName: "10_Debarment_Notice_State_Grid.pdf",
    sha256: "fdc0b081f5a3989fd91dc185f619bd624b39ae3f918772b3b1ce48dcb7fc25fb",
    documentType: "DEBARMENT_NOTICE",
    bidderId: "SYN-BDR-000006",
    vendorName: "Konkan Vector Hydraulics & Pneumatics Partnership",
    requirementIds: ["req-008"],
    verificationProvider: "DEBARMENT",
    extractedText:
      "STATE ELECTRICITY INFRASTRUCTURE BOARD (SEB) — OFFICIAL BLACKLISTING & DEBARMENT ORDER. Debarred Organization: Konkan Vector Hydraulics & Pneumatics Partnership (PAN: CQVCK7494I). Issuing Authority: State Electricity Infrastructure Board (SEB). Debarment Period: 01-Oct-2025 to 30-Sep-2027 (ACTIVE 2-YEAR DEBARMENT). Status: DEBARRED FROM GOVERNMENT TENDERS.",
    structuredFields: [
      { key: "DEBARMENT_STATUS", label: "CPPP Debarment Status", value: "DEBARRED FROM GOVT TENDERS", confidence: 0.94 },
      { key: "DEBARMENT_PERIOD", label: "Debarment Period", value: "01-Oct-2025 to 30-Sep-2027", confidence: 0.94 },
    ],
  },
];
