"use client";

import PublicLayout from "@/components/layout/PublicLayout";
import { FileText } from "lucide-react";

export default function TermsPage() {
  return (
    <PublicLayout>
      <div className="py-12 px-4 sm:px-8 max-w-4xl mx-auto">
        <div className="bg-white p-8 rounded-2xl border border-[#dce6f0] shadow-xs space-y-6">
          <div className="flex items-center gap-3 border-b border-[#edf1f4] pb-4">
            <FileText className="text-[#004e8a]" size={28} />
            <div>
              <h1 className="text-2xl font-extrabold text-[#002b4d]">Terms of Service & Usage Governance</h1>
              <p className="text-xs text-[#5c6b73]">Governing Usage of BIDSETU Platform & DATASETU Statutory Services</p>
            </div>
          </div>

          <div className="text-xs text-[#4a5568] space-y-4 leading-relaxed">
            <h3 className="text-sm font-bold text-[#002b4d]">1. Authorized Platform Usage</h3>
            <p>
              BIDSETU is provided for official procurement evaluation by buyers and legitimate bid submission by vendors registered on government portals. Misrepresentation of GSTIN, PAN, or financial numbers is punishable under the Indian Penal Code and Prevention of Corruption Act.
            </p>

            <h3 className="text-sm font-bold text-[#002b4d]">2. Automated Evaluation Disclaimer</h3>
            <p>
              AI compliance scores generated by BIDSETU serve as automated decision support for Tender Evaluation Committees (TEC). Procurement officers retain final decision authority under GFR Rule 173.
            </p>
          </div>
        </div>
      </div>
    </PublicLayout>
  );
}
